name: dart_valve_kit
description: Valve kit is a package for Valve formats (VDF, VTF, etc.) made on Dart.
version: 1.0.0
repository: https://github.com/ma3rd-nepon/dart-valve-kit

environment:
  sdk: ^3.12.2

dependencies:
  path: ^1.9.0
  image: ^4.9.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
